# Site settings
title: Copas Seo
description: "Copas seo: Berbagi Informasi Adsense, Seo Blogging dan Seo Template"
url: https://copas-seo.my.id
author: Acha81

# Build setting
markdown: kramdown
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page:num/

compress_html:
  clippings: all

input_types:
  - text
  - textarea
  - email
  - date
  - checkbox
  - radio
  - number
  - submit
  - recaptcha

form_engines:
  - cloudcannon
  - formspree
  - formbucket
  - netlify

# This will require each of these plugins automatically.
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
