title: Copas <span>Seo</span>
email: acha_jie@rocketmail.com
description: "Copas <span>Seo</span> Berbagi Informasi Adsense, <span>Seo</span> Blogging dan <span>Seo</span> Template"
author: Acha81 <span>Design</span>
url: "copas-seo.my.id"
twitter_username: Acha81
facebook_username: Acha81
instagram_username: acha81
youtube_username: Acha81
telegram_username: Acha81
github_username:  Copas-Seo

# Build settings
theme: minima
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page:num/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

plugin: [jekyll-paginate]

input_types:
  - text
  - textarea
  - email
  - date
  - checkbox
  - radio
  - number
  - submit
  - recaptcha

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
