# Site settings
title: Copas Seo
permalink: /:title
description: "Copas Seo : Berbagi Informasi Adsense, Seo Blogging dan Seo Template"
author: Acha81
url: https://copas-seo.my.id

# Build setting
markdown: kramdown
destination: ./_site
permalink: /:title
paginate: 6
paginate_path: /page:num/

input_types:
  - text
  - textarea
  - email
  - date
  - checkbox
  - radio
  - number
  - submit
  - recaptcha

form_engines:
  - cloudcannon
  - formspree
  - formbucket
  - netlify

# This will require each of these plugins automatically.
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
