title: Copas Seo
permalink: /:title
description: "Berbagi Informasi Adsense Blogging dan Template"
author: Acha81
url: https://copas-seo.my.id

# Build setting
markdown: kramdown
paginate: 6
paginate_path: "/blog/page:num/"

input_types:
  - text
  - textarea
  - email
  - date
  - checkbox
  - radio
  - number
  - submit
  - recaptcha

form_engines:
  - cloudcannon
  - formspree
  - formbucket
  - netlify

# This will require each of these plugins automatically.
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate