# Site settings
title: Copas Seo
permalink: /:title
description: "Berbagi Informasi Adsense Blogging dan Template"
author: Acha81
url: https://copas-seo.github.io/

plugins: 
      - jekyll-sitemap
      - jekyll-seo-tag