title: Copas Seo
email: acha_jie@rocketmail.com
description: "Copas Seo Berbagi Informasi Adsense, Seo Blogging dan Seo Template"
author: Acha81 Design
url: "https://copas-seo.my.id"
twitter_username: Acha81
facebook_username: Acha81
instagram_username: acha81
youtube_username: Acha81
telegram_username: Acha81
github_username:  Copas-Seo

# Build settings
permalink: acha
markdown: kramdown
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page:num/
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
