title: Copas Seo
permalink: /:title
description: "Berbagi Informasi Adsense Blogging dan Template"
author: Acha81
url: https://copas-seo.my.id

input_types:
  - text
  - textarea
  - email
  - date
  - checkbox
  - radio
  - number
  - submit
  - recaptcha

form_engines:
  - cloudcannon
  - formspree
  - formbucket
  - netlify

plugins:
    - jekyll-feed
    - jekyll-seo-tag
